# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  dev.lishaoy.net:
    site_hosts:
      - canonical: dev.lishaoy.net
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: persilee@foxmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
